export type Lead = {
  cnpj: string;
  cnpj_basico?: string | null;
  cnpj_ordem?: string | null;
  cnpj_dv?: string | null;
  matriz_filial?: string | null;
  nome_fantasia?: string | null;
  razao_social?: string | null;
  natureza_juridica?: string | null;
  natureza_juridica_desc?: string | null;
  qualificacao_responsavel?: string | null;
  ente_federativo_responsavel?: string | null;
  porte_empresa?: string | null;
  capital_social?: number | null;
  situacao_cadastral?: string | null;
  situacao_cadastral_desc?: string | null;
  motivo_situacao_cadastral?: string | null;
  motivo_situacao_desc?: string | null;
  data_situacao_cadastral?: string | null;
  data_inicio_atividades?: string | null;
  cnae_fiscal?: string | null;
  cnae_fiscal_desc?: string | null;
  cnae_fiscal_secundaria?: string | null;
  nome_cidade_exterior?: string | null;
  pais_codigo?: string | null;
  tipo_logradouro?: string | null;
  logradouro?: string | null;
  numero?: string | null;
  complemento?: string | null;
  bairro?: string | null;
  cep?: string | null;
  uf?: string | null;
  municipio_codigo?: string | null;
  municipio?: string | null;
  ddd1?: string | null;
  telefone1?: string | null;
  ddd2?: string | null;
  telefone2?: string | null;
  ddd_fax?: string | null;
  fax?: string | null;
  correio_eletronico?: string | null;
  situacao_especial?: string | null;
  data_situacao_especial?: string | null;
  opcao_simples?: string | null;
  data_opcao_simples?: string | null;
  data_exclusao_simples?: string | null;
  opcao_mei?: string | null;
  data_opcao_mei?: string | null;
  data_exclusao_mei?: string | null;
  socios?: Socio[];
};

export type Socio = {
  cnpj?: string | null;
  identificador_de_socio?: string | null;
  nome_socio?: string | null;
  cnpj_cpf_socio?: string | null;
  qualificacao_socio?: string | null;
  qualificacao_socio_desc?: string | null;
  data_entrada_sociedade?: string | null;
  pais?: string | null;
  representante_legal?: string | null;
  nome_representante?: string | null;
  qualificacao_representante_legal?: string | null;
  faixa_etaria?: string | null;
  ddd1?: string | null;
  telefone1?: string | null;
  ddd2?: string | null;
  telefone2?: string | null;
  correio_eletronico?: string | null;
};

export type SearchParams = {
  q?: string;
  uf?: string;
  situacao?: string;
  cnae?: string;
  municipio?: string;
  com_telefone?: string;
  com_socio?: string;
  limit?: number;
  offset?: number;
};
